"""
Embedding model abstraction.

Dense vs sparse embeddings
───────────────────────────
Dense (what we use here):
  - A vector of ~384–3072 floats representing the semantic meaning of a text.
  - Similar texts → similar vectors (high cosine similarity).
  - Generated by a neural encoder (sentence-transformers, OpenAI, etc.).
  - Good at semantic similarity: "fast car" ≈ "quick automobile".

Sparse (BM25, TF-IDF):
  - High-dimensional but mostly zeros: one dimension per vocabulary term.
  - Good at exact keyword matching: "TCP/IP RFC 793" → precise retrieval.
  - Complementary to dense: combining both (hybrid search) outperforms either.

Embedding model choice
───────────────────────
  DeterministicEmbedder  Consistent hash-based fake. For offline unit tests only.
  SentenceTransformerEmbedder  Local inference. No API cost. Downloads model once.
  OpenAIEmbedder  API call. Best quality. Costs money. Needs OPENAI_API_KEY.

Dimensions: larger = more expressive but more storage / slower similarity.
  all-MiniLM-L6-v2:   384 dims (~22M params, fast, good quality)
  text-embedding-3-small: 1536 dims (best OpenAI small model, cheap)
  text-embedding-3-large: 3072 dims (highest quality, 5× cost of small)
"""

import hashlib
import math
from typing import Protocol, runtime_checkable


@runtime_checkable
class Embedder(Protocol):
    @property
    def dimension(self) -> int: ...

    def embed(self, texts: list[str]) -> list[list[float]]: ...

    def embed_one(self, text: str) -> list[float]: ...


class DeterministicEmbedder:
    """
    Consistent fake embedder for offline tests.

    Generates a unit vector from the SHA-256 hash of the text.
    NOT semantically meaningful — similar texts will NOT have similar vectors.
    Use only in tests. For production use SentenceTransformerEmbedder or OpenAIEmbedder.
    """

    def __init__(self, dimension: int = 128) -> None:
        self._dimension = dimension

    @property
    def dimension(self) -> int:
        return self._dimension

    def embed(self, texts: list[str]) -> list[list[float]]:
        return [self.embed_one(t) for t in texts]

    def embed_one(self, text: str) -> list[float]:
        # Extend SHA-256 digest to self._dimension bytes, then map each byte
        # to [-1, 1] as a float.  Avoids IEEE-754 NaN/Inf that arise when
        # unpacking arbitrary hash bytes as float32 with struct.unpack.
        raw = bytearray(hashlib.sha256(text.encode()).digest())
        while len(raw) < self._dimension:
            raw += bytearray(hashlib.sha256(bytes(raw)).digest())

        vec = [(b - 127.5) / 127.5 for b in raw[: self._dimension]]
        mag = math.sqrt(sum(x * x for x in vec))
        return [x / mag for x in vec] if mag > 0 else vec


class SentenceTransformerEmbedder:
    """
    Local embedding using sentence-transformers (no API cost).
    Downloads the model on first instantiation (~90 MB for all-MiniLM-L6-v2).
    Subsequent calls use the cached local model.

    Requires: uv sync --extra rag
    """

    DEFAULT_MODEL = "all-MiniLM-L6-v2"

    def __init__(self, model: str = DEFAULT_MODEL) -> None:
        from sentence_transformers import SentenceTransformer  # lazy import

        self._st = SentenceTransformer(model)
        dim = self._st.get_sentence_embedding_dimension()
        self._dimension = dim if dim is not None else 384

    @property
    def dimension(self) -> int:
        return self._dimension

    def embed(self, texts: list[str]) -> list[list[float]]:
        return self._st.encode(texts, show_progress_bar=False).tolist()  # type: ignore[union-attr]

    def embed_one(self, text: str) -> list[float]:
        return self.embed([text])[0]


class OpenAIEmbedder:
    """
    Embedder using OpenAI's text-embedding-3-small (or -large).
    Best quality; costs ~$0.02 per million tokens.

    Requires: OPENAI_API_KEY in environment.
    """

    DEFAULT_MODEL = "text-embedding-3-small"
    _DIMENSIONS = {"text-embedding-3-small": 1536, "text-embedding-3-large": 3072}

    def __init__(self, model: str = DEFAULT_MODEL, api_key: str | None = None) -> None:
        from openai import OpenAI  # lazy import

        self._client = OpenAI(api_key=api_key)
        self._model = model
        self._dimension = self._DIMENSIONS.get(model, 1536)

    @property
    def dimension(self) -> int:
        return self._dimension

    def embed(self, texts: list[str]) -> list[list[float]]:
        response = self._client.embeddings.create(model=self._model, input=texts)
        return [item.embedding for item in response.data]

    def embed_one(self, text: str) -> list[float]:
        return self.embed([text])[0]
